### PR TITLE
[WIP] Tasks workflow redesign

### PR DESCRIPTION
**Pull request by batpad**
Refs https://github.com/orma/openroads-vn-analytics/issues/433

This PR should be fully functional with the following TODOs remaining:

 - Show Task Number - DONE
 - Show Task Count - DONE
 - Show Last Updated time - DONE
 - Show Province and District of each road
 - Get Province search to work again - DONE

Some of these depend on back-end tasks. But @ricardomestre will be great if you can pull this and play around, and give feedback on the functionality - especially, I think the map styling can be improved in the various steps - it might help to play with it a bit and then you can suggest changes?

@danielfdsilva I need to still run this through the linter, but will be great if I can get a quick general review and any suggestions on the code. Thank you!

### CODE REVIEW

**Comment by batpad** [comment]
Update here:

Have gotten through the TODOs above except for "Showing Province / District" for each road, which is dependent on another backend change.

This requires an updated `openroads-api` code-base to work, currently in this PR: https://github.com/orma/openroads-vn-api/pull/112 - which adds the task `updated_at` field.

@ricardomestre one question: it seems like the button saying "Solve <x>" as well as the "Status" button are clickable - I'm not sure where clicking on them should route the user.

@geohacker - one thing I'm having a bit of trouble understanding is how the `pending` field for Tasks is used in the database. I can see we were doing a bunch of calls to it based on different user actions, and I'm not sure if I've gotten that part right with the new work-flow, since I'm a bit unsure what it's meant to do.

Just to update what's remaining here:

 - [ ] Add province / district information in list view (once backend supports this)
 - [ ] Make the linter pass
 - [ ] Changes to map styling in different stages, if any (needs input from @ricardomestre )

Otherwise, this *should* be all working - will be great to have more folks test it and report bugs.

**Comment by geohacker** [comment]
> one thing I'm having a bit of trouble understanding is how the pending field for Tasks is used in the database.

@batpad I'm unsure as well. @dereklieu do you know what this field gets used for? This is set to false by default.

**Comment by geohacker** [comment]
@batpad thank you for getting this so close. I just made the last updated to show hours instead of days, since we update the tasks usually every day.

**Comment by dereklieu** [comment]
@geohacker @batpad the pending column is a hold-over from when we would continually (and frequently) reprocess the entire road network, and not just what had recently been changed. 

A task would be marked=true as pending when a user performed any action to it in the tasks interface. This meant that it would no longer be shown to other users until the task script ran again, at which point two scenarios are possible:

1. The issue is fixed and the road is not included in the re-created tasks db.
2. The issue is not fixed and another task is created with the pending flag marked as `false`.

I don't think we really need it now that we're not reprocessing geometries.

**Pull request merged**
