### PR TITLE
Feature/active road

### LINKED ISSUE #270: Clarify which road was zoomed to, when navigating or using search
When a user zooms to a particular VPRoMMS road ID using search functionality, visually indicate which path(s) constitute that road. (Currently, zooming to a road ID via search works, but it’s unclear which line represents the road in question.)

### PR DESCRIPTION
**Pull request by jameslaneconkling**
closes partially #270

### CODE REVIEW

**Comment by jameslaneconkling** [comment]
a minor concern on this is style: roads are already colored black/red/green.  The highlight needs to be a different color, but the remaining colors in the site's style guide (blue and yellow) don't look great.  I ended up using a desaturated version of the site's red, which gets the job done, but isn't great.

Maybe worth thinking about changing road coloring to a more flexible color ramp ([d3 has good examples](https://github.com/d3/d3-scale-chromatic))

**Comment by jameslaneconkling** [comment]
Oh yeah, and this doesn't cover iD...

**Comment by mileswwatkins** [comment]
@jameslaneconkling, what about this Mapbox `paint` object for the underlay?

```
          paint: {
            'line-width': 30,
            'line-color': '#D3D3D3'
          },
```

Agree that we need a color that doesn't interfere with the user's ability to read the current red-to-green ramp of road IRI.

**Comment by mileswwatkins** [comment]
Otherwise, everything generally looks good! I found one minor bug, which is that if you're in `/explore?activeRoad=212TH00008`, and then click on `Explore` in the page header, you trigger a JS error that's shown in the console:

screen shot 2017-12-22 at 16 17 37

**Pull request merged**
