### PR TITLE
Feature/tasks count

### LINKED ISSUE #224: Tasks view should show "tasks remaining" count

### PR DESCRIPTION
**Pull request by jameslaneconkling**
Closes #224

Includes a significant refactor to the tasks redux module and the tasks page.

### CODE REVIEW

**Comment by jameslaneconkling** [comment]
Fixed the lint issue by disabling linting for those lines.  A more proper fix will require refactoring the react/mapbox-gl bindings (tracked #288).

**Comment by jameslaneconkling** [comment]
also closes #281

**Comment by mileswwatkins** [comment]
Awesome, working great. As we just discussed, only thing left is to re-fetch `tasks/count` after each `Finish Task` click, and update the number shown. Once that change is made, then this PR is good to merge.

**Comment by jameslaneconkling** [comment]
@mileswwatkins OK, took a little bit of extra wrangling to get the task api calls cleaned up.  But should be in place now.

**Comment by mileswwatkins** [comment]
Tested this locally. The task count does successfully decrement, but I'm seeing errors when I actually perform a task and then click "finish task" or even "skip task." Do you know what could be causing this?

screen shot 2017-11-30 at 14 06 23

**Comment by mileswwatkins** [comment]
@jameslaneconkling is opening a separate bugfix to handle the above error, which we talked about. The feature (only tangentially related to the bug) is complete.

**Pull request merged**
